apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: sakthisaransss55/portfolio:latest
        resources:
          limits:
            memory: "100Mi"
            cpu: "150m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portfolioservice
spec:
  type: ClusterIP
  selector:
    app: portfolio
  ports:
  - port: 80
    targetPort: 80

